---
# DEPLOYMENT
kind: pipeline
name: deployment
type: docker

trigger:
  branch:
    - main
  event:
    - push

steps:
- name: build
  image: node:18.16.1-alpine3.18
  volumes:
  - name: northbit
    path: /northbit
  commands:
  - npm config set legacy-peer-deps true
  - npm ci
  - npm run patch
  - cp /northbit/frontend/.env.local ./.env.production.local
  - npm run build
  - cp ./build/northbit.zip ./northbit.zip

# Send production build files to server
- name: scp-production
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: ssh_host
    user:
      from_secret: ssh_user
    key:
      from_secret: ssh_private_key
    port:
      from_secret: ssh_port
    overwrite: true
    target: /home/putu/portalnesia/nodejs/northbit/frontend
    source:
    - ./northbit.zip
    - ./package.json
    - ./package-lock.json
  depends_on:
  - build

# Update production server
- name: ssh-production
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: ssh_host
    user:
      from_secret: ssh_user
    key:
      from_secret: ssh_private_key
    port:
      from_secret: ssh_port
    command_timeout: 5m
    script_stop: true
    script: |
      export NVM_DIR=~/.nvm
      source ~/.nvm/nvm.sh
      cd ~/portalnesia/nodejs/northbit/frontend
      npm ci --omit=dev
      npm run reload
  depends_on:
  - scp-production

- name: discord
  image: appleboy/drone-discord
  depends_on:
  - ssh-production
  when:
    status:
    - success
    - failure
  settings:
    webhook_id:
      from_secret: unicare_discord_id
    webhook_token:
      from_secret: unicare_discord_token
    avatar_url: https://content.portalnesia.com/icon/PN-Logo.png
    username: Portalnesia
    message: |
      {{repo.namespace}}/{{repo.name}}
      
      Deployment
      {{#success build.status}}
      Status: succeeded ✅
      {{else}}
      Status: failed ❌
      See: {{build.link}}
      {{/success}}
      
      by. Portalnesia CI/CD

volumes:
- name: northbit
  host:
    path: /home/putu/portalnesia/nodejs/northbit

...